## Numpy Practice Questions

### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally. 

In [2]:
import numpy as np
A = np.array([[1, 2, 3],[7, 6, 9]])
B = np.array([[7, 8, 9],[10, 11, 12]])
stacked_v = np.vstack((A, B))
stacked_h = np.hstack((A, B))

print("Stacked Vertically:")
print(stacked_v)

print("\nStacked Horizontally:")
print(stacked_h)

Stacked Vertically:
[[ 1  2  3]
 [ 7  6  9]
 [ 7  8  9]
 [10 11 12]]

Stacked Horizontally:
[[ 1  2  3  7  8  9]
 [ 7  6  9 10 11 12]]


### 2. Find common elements between A and B. [Hint : Intersection of two sets]

In [5]:
A = A.flatten()
B = B.flatten()

common = np.intersect1d(A, B)
common

array([7, 9])

In [6]:
A

array([1, 2, 3, 7, 6, 9])

In [8]:
result = A[np.where((A >= 5) & (A <= 10))]
print(result)

[7 6 9]


In [9]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [10]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
filtered = iris_2d[np.where((iris_2d[:,2] > 1.5)& (iris_2d[:,0] < 5.0))]

filtered

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## Practice Questions for Pandas

### 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [18]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [27]:
filter_row = df.iloc[::20, [0,1,2]]
filter_row

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

### 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [34]:
min_mean = df['Min.Price'].mean()
min_mean

17.118604651162787

In [37]:
df['Min.Price'] = df['Min.Price'].fillna(min_mean)
df['Min.Price'].isna().value_counts()

False    93
Name: Min.Price, dtype: int64

In [38]:
max_mean = df['Max.Price'].mean()
max_mean
df['Max.Price'] = df['Max.Price'].fillna(max_mean)
df['Max.Price'].isna().value_counts()

False    93
Name: Max.Price, dtype: int64

### 3. How to get the rows of a dataframe with row sum > 100?

In [39]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [40]:
df

0   1   2   3
0   11  13  25  32
1   21  13  34  26
2   17  10  20  33
3   28  25  22  37
4   30  36  22  34
5   32  30  18  25
6   34  36  35  11
7   33  35  12  11
8   10  37  13  15
9   16  17  18  35
10  18  17  25  29
11  37  14  27  37
12  22  13  18  14
13  19  27  31  34
14  18  11  16  21

In [41]:
row_sum = df.sum(axis = 1)

print_row = df[row_sum > 100]
print_row

0   1   2   3
3   28  25  22  37
4   30  36  22  34
5   32  30  18  25
6   34  36  35  11
11  37  14  27  37
13  19  27  31  34